### ISSUE TITLE
no result after dijkstra ==> challenge  with osm2pgrouting

### ISSUE THREAD

**Issue by SchorschDerBaer** [pgRouting/pgrouting#2371] opened 2022-09-20 07:18 UTC
Hi,
pgrouting seems to calculate routes (~12 sec.) but the result is empty. Field names are there but 0 records. Also the message says the same.

source and target are taken form source and target fields or the vertices table.both have the same result: 0 records. data were built like:

1. download germany-latest.osm.pbf
2. extract to *.osm
3. reduced with osmfilter --keep "highway=primary =secondary ..... 
4. loaded with osm2pgrouting

the dataset looks ok. several queries were tested. 

please let me know how to solve this.
Thank you in advance.

Cheers Georg

**Comment by cvvergara** [comment] 2022-09-20 16:34
Check how many components there are in the graph. (more than one component means that the graph is disconnected)
and specially if the starting and destination points are in the same component, because if they are not there will never be a path found.

**Comment by SchorschDerBaer** [comment] 2022-09-20 17:46
Hi Vicky,
Yes you are right the graph is Not connected. Did not see because postgis
only showing 1000 features>> allways scattert. the problem is either
osmfilter or osmium or osm2pgrouting.

Do you have any idea?

Gracias

Georg

Vicky Vergara ***@***.***> schrieb am Di., 20. Sept. 2022,
18:34:

**Comment by cvvergara** [comment] 2022-09-20 19:10
In the case of the well known Dijkstra algorithm... I can only blame the data. ;-)

With the components functions you are analyzing the quality of the data.
- Maybe your bounding box was too small?
- maybe you removed features that should not be removed
- maybe you need to adjust the configuration file for osm2pgrouting you your needs
- maybe there is a segment that has not been captured yet on the open street map data
- maybe is something I can not think of
- maybe a bit of everything above


Check this section:
https://docs.pgrouting.org/latest/en/pgRouting-concepts.html#check-the-routing-topology

Also even with so many issues, you can use:
https://docs.pgrouting.org/latest/en/pgr_nodeNetwork.html
to connect components.

**Comment by SchorschDerBaer** [comment] 2022-09-20 19:22
I used PGRouting before ... all-time top!

The problem might be osm2PGRouting it gives errors.

[image: image.png]

That's my status now. And with 28% of the data, the net is not a net.

before I did:
osmium tags-filter germany-latest.osm.pbf -v
wr/highway=primary,secondary,trunk,tertiary,residential,primary_link,secondary_link,trunk_link,tertiary_link,living_street,service
-o ways_V4.osm.pbf

then:

 osmium cat ways_V4.osm.pbf -o ways_V4.osm

then:
osm2pgrouting --f ways_V4.osm --conf mapconfig.xml --dbname
VersatelNetRouting --username dataloader --password ???? --clean

it looks like osm2 pgrouting is the challenge. Is there a limit?

Any idea?

Thank you in advance. Gracias.

Cheers Georg





Am Di., 20. Sept. 2022 um 21:10 Uhr schrieb Vicky Vergara <
***@***.***>:

**Comment by cvvergara** [comment] 2022-09-20 23:30
osm2pgrouting has its own problems like it can not handle big files, it must have been answered on the issue tracker before
This is pgRouting issue tracker.
I will close this issue as the problem is not on pgRouitng.
See you on osm2pgrouting issue tracker (if you think you need to open an issue there)

**Closed by cvvergara** 2022-09-20 23:30 UTC
Labels: Question

**Comment by SchorschDerBaer** [comment] 2022-09-21 08:55
as discussed above the issue is with osm2pgrouting. 

setting:     --chunk 25000000 did the trick.
