### ISSUE TITLE
Patch for pgr_kdijkstra returning wrong edges/cost

### ISSUE THREAD

**Issue by xcalibur666** [pgRouting/pgrouting#229] opened 2013-12-16 07:28 UTC
There is a problem with pgr_kdijkstra, that you cannot count on the edges and costs returned by the algorithms.

This is caused by, that the first edge found between two nodes is returned, and if two or more edges between two nodes exist, then there is a very real risk, that the NOT optimal edge is returned.

I've created a patch for the pgr_kdijkstra at
https://gist.github.com/xcalibur666/7983406
Someone should have a second look at it, as the patch is created and tested only locally.

The same problem existed earlier for Dijkstra and A*, and I created a patch for these algorithms 10 months ago, https://github.com/pgRouting/pgrouting/issues/78

I think it is a serious problem, that people cannot count on the output returned by pgRouting. This should be stated very clearly in the documentation, if people should be able to use pgRouting for serious business. A better way, I think, could be to return null in the id3 and cost output values, when the algorithm is not guaranteed to return correct output.

**Comment by ArGeBre** [comment] 2015-05-21 14:16
Hi there. I am fairly new to pgRouting. I am working on a project making use of pgRouting for simulating a dynamic traffic distribution.

I ran into the same problem with the pgr_kdijkstra implementation, giving me routes containing edges with a cost value of 100000 (which is in fact the reverse_cost as the edge was being traversed in reverse direction).

I tried applying the patch to the latest release (pgrouting-2.0.0-0-gd6ed2cb master) and the current develop branch, but the builds yield absolutely unusable results:
<table border="1"><tr BGCOLOR="#CCCCFF"><th>seq</th><th>id1</th><th>id2</th><th>id3</th><th>cost</th></tr>
<tr><td>-1896315272</td><td>32687</td><td>-1896315270</td><td>32685</td><td>0</td></tr>
<tr><td>0</td><td>2</td><td>-53492975</td><td>1073541360</td><td>0</td></tr>
<tr><td>1061158719</td><td>214908146</td><td>-251658482</td><td>-196672</td><td>0</td></tr>
<tr><td>3</td><td>446584</td><td>446584</td><td>-1</td><td>0</td></tr>
</table>

This bug is a serious show-stopper for my current project, so I am hoping that it will be fixed in the near future. Is there a schedule for the next release. The 2.1.0 milestome still seems a long way away...

Thanks,
Arne

**Comment by cvvergara** [comment] 2015-05-21 14:36
@ArGeBre 
To have a clear idea of what is going on, can you please:
Run your query using develop branch.
Post the query you are running.

**Comment by woodbri** [comment] 2015-05-21 20:15
Yeah, to be a little more specific we need to be able to run the same query to debug the problem. so if you can create a simple example that reproduces the issue that would be a great help. Otherwise if you can ``pg_dump -Fp -f data.sql -t some_table ...`` and include you query we will see what we can figure out.

**Comment by ArGeBre** [comment] 2015-05-22 08:20
Thanks for the quick responses. I will investigate further and post the scenario...

**Comment by ArGeBre** [comment] 2015-05-22 11:17
OK, the corrupt output does not seem to be related to the patch, because even the unpachted installation produced the same mess of numbers. It seems to be more an installation related issue.
My previous installation was a debian package which I uninstalled using:
<code>apt-get remove postgresql-9.4-pgrouting</code>
after that I compiled and installed from the sources as described in the build guide.
<code>make</code>
<code>make install</code>
which apparently is not enough. I had to <code>drop extension pgrouting</code> and <code>create extension pgrouting</code> in order to make it work. Might be a good idea to mention that in the build guide :-)
I now get reasonable results. However I have not been able to verify whether or not the patch fixes the original problem.
Sorry about the fuzz...

**Comment by ArGeBre** [comment] 2015-07-20 11:06
Hi guys,

I'm back :-) Unfortunately my attempts to get the patch working still failed. For some reason I thought that I had overcome the problems, but it seems I was wrong.

My environment:
* Debian 8.1 (jessie)
* PostgreSQL 9.4.3 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
* postgis Version 2.1.7 
* pgrouting Version 2.0.0 / postgresql-9.4-pgrouting (2.0.0-3) 

I downloaded and patched the original source package from Debian. Running the sample query on the sample data:

SELECT seq, id1 AS path, id2 AS node, id3 AS edge, cost
  FROM pgr_kdijkstraPath(
      'SELECT id, source, target, cost FROM edge_table',
      10, array[4,12], false, false
);

gives me these results:
<table border="1"><tr BGCOLOR="#CCCCFF"><th>seq</th><th>path</th><th>node</th><th>edge</th><th>cost</th></tr>
<tr><td>-1833371160</td><td>32556</td><td>-1833371159</td><td>32555</td><td>0</td></tr>
<tr><td>-1780946240</td><td>32556</td><td>49</td><td>0</td><td>0</td></tr>
<tr><td>0</td><td>1</td><td>-1780879835</td><td>32555</td><td>0</td></tr>
<tr><td>-1780879936</td><td>32556</td><td>-1780879923</td><td>32555</td><td>0</td></tr>
<tr><td>4</td><td>4</td><td>4</td><td>-1</td><td>0</td></tr>
<tr><td>4</td><td>32556</td><td>1</td><td>1074790400</td><td>0</td></tr>
<tr><td>12</td><td>1</td><td>1</td><td>1073741824</td><td>0</td></tr>
<tr><td>7</td><td>12</td><td>12</td><td>-1</td><td>0</td></tr>
</table>

Interestingly the pgr_kdijkstraCost() function returns the correct result.

Maybe someone can reproduce the problem and give me some hints.

Thanks,
Arne

**Comment by cvvergara** [comment] 2015-07-20 12:27
@ArGeBre 
pgr_kdijstraCost and pgr_kkdijstraPath are not modified in version 2.1
you can test pgr_dijkstra with the new signatures.

**Comment by ArGeBre** [comment] 2015-07-21 08:28
I will try. Which version shall I take? According to the docs the 
pgr_dijkstra function supports the one-to-many, many-to-one and 
many-to-many signatures only in version 3.0 but I cannot find it anywhere.

Arne

Am 20.07.2015 um 14:27 schrieb Vicky Vergara:

**Comment by cvvergara** [comment] 2015-07-21 12:01
https://github.com/pgRouting/pgrouting/releases/tag/pgrouting-2.1.0-alpha1

**Comment by cvvergara** [comment] 2015-07-21 12:07
V2.1 includes the signatures of V2.0 and the new signatures of V3.0 for pgr_dijkstra, pgr_ksp, and pgr_drivingDistance.

**Comment by cvvergara** [comment] 2015-11-23 23:54
This issue, Title is about pgr_kdijkstra but the comments are only about pgr_kdijkstraPath

See #333
As pgr_kdijkstraPath is going to be deprecated in favor of pgr_dijkstra
This bug will disappear.

**Comment by cvvergara** [comment] 2016-02-25 17:44
Deprecating pgr_kdijstraCost please use pgr_dijkstraCost (one to many)
pgr_kdijstraCost Its being fixed by wrapping it with the results of pgr_dijkstraCost (one to many)

Deprecating pgr_kdijstraPath please use pgr_dijkstra (one to many)
pgr_kdijstraPath Its being fixed by wrapping it with the results of pgr_dijkstra (one to many)

**Closed by cvvergara** 2016-02-25 17:44 UTC
Labels: Bug Report, DijkstraCost, Fixed on dev-2.2
