### ISSUE TITLE
pgr_kdijkstraCost allows only integer source and target fields in edges sql.

### ISSUE THREAD

**Issue by nextstopsun** [pgRouting/pgrouting#538] opened 2016-04-03 10:14 UTC
### Expected behavior and actual behavior
While pgr-dijkstra can accept bigint (but only if the last parameter `boolean has_rcost` is not set), pgr_kdijkstraCost can't.
I'm trying to create a distance matrix and want to use pgr_kdijkstraCost for that, but my network is large and uses bigints as node id's.

### Steps to reproduce the problem
Just cast fields source and target columns in an edge sql string parameter to bigint. 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
Postgresql 9.5, POSTGIS="2.2.1 r14555", Ubuntu 14.04

**Comment by cvvergara** [comment] 2016-04-03 23:57
@nextstopsun 
kdijsktraCost was designed to use int4 as you can see in the documentation.
and its only one to many and is being deprecated in version 2.2. (but the signature has to remain during the transition to 3.x)

pgr_dijkstraCost  (wihtout the k) works for:
one to one, one to many 
many to one
and many to many
and that one is designed to use bigint

"While pgr-dijkstra can accept bigint (but only if the last parameter boolean has_rcost is not set), "
For V2.1 or greater: the signatrue dos not have "has_rcost" flag, because the code detects if it has it or not. 
But the V2.0 signature that has the "has_rcost" flag has to be kept because if someone already made code with it, we can not brake it during the 2.x versions.

None of the rewritten function need "has_rcost" flag because the code can detect now if it has it or not.

**Comment by nextstopsun** [comment] 2016-04-04 10:06
@cvvergara Ok, thanks, I'll then stick to many-to-many `pgr_dijkstra` function to create a matrix. Does `pgr_bdDijkstra` have a one-to-many or a many-to-many variant? I'm guessing Bi-directional should work faster then plain Dijkstra.

**Comment by cvvergara** [comment] 2016-04-04 16:18
@nextstopsun 
`pgr_bdDijkstra`:  only works for int4, undirected flag + has_rcost flag give wierd results on some inputs.
 No "family" of functions made.
 Like you said "it should work faster", but I haven't herd of anyone making a benchmark test vs  pgr_dijkstra, to see if for this implementation(s) is true.

 I am closing the issue due to the fact that `pgr_kdijstraCost` is deprecated in V2.2.

**Closed by cvvergara** 2016-04-04 16:18 UTC
