### ISSUE TITLE
Compile warning branch develop, tag pgrouting-2.1.0-alpha1

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#373] opened 2015-07-22 14:55 UTC
I'm getting the following warning compiling on Ubuntu 14.04:
branch "develop"
tag pgrouting-2.1.0-alpha1

```
[ 10%] Building CXX object src/apsp_johnson/src/CMakeFiles/apsp_johnson.dir/apsp_johnson_boost_wrapper.cpp.o
/home/woodbri/work/pgrouting/src/apsp_johnson/src/apsp_johnson_boost_wrapper.cpp: In function 'int boost_apsp_johnson(edge_apsp_johnson_t*, int, edge_apsp_johnson_t**, int*, char**)':
/home/woodbri/work/pgrouting/src/apsp_johnson/src/apsp_johnson_boost_wrapper.cpp:100:40: warning: '*((void*)(& ei)+32).__gnu_cxx::__normal_iterator<boost::detail::stored_edge_property<long unsigned int, Edge>*, std::vector<boost::detail::stored_edge_property<long unsigned int, Edge>, std::allocator<boost::detail::stored_edge_property<long unsigned int, Edge> > > >::_M_current' may be used uninitialized in this function [-Wmaybe-uninitialized]
   graph_traits<graph_t>::edge_iterator ei, eend;
                                        ^
```

**Comment by woodbri** [comment] 2015-07-22 14:58
also get this in branch "develop_2_1_0"

**Comment by cvvergara** [comment] 2015-07-22 16:55
Non of the travis show that error:
https://travis-ci.org/pgRouting/pgrouting/jobs/72064827#L1870
This is the code:
  graph_traits<graph_t>::edge_iterator ei, eend;
  for (tie(ei, eend) = boost::edges(graph); ei != eend; ei++) {
It gets initialized on the tie.
Can you tell me what version of boost are you using?

**Comment by woodbri** [comment] 2015-07-22 17:01
Boost version: 1.54.0

**Comment by cvvergara** [comment] 2015-07-22 17:06
besides the warning, do the tests pass in with boost 1.54?

**Comment by sanak** [comment] 2015-07-22 17:12
I am not sure the issue is same as my private `master-msvc` branch,
but on Windows Visual Studio compiler, `tie` => `boost::tie` conversion was necessary.
https://github.com/sanak/pgrouting4w/commit/b3743933dad6b602e3fa02a11b623cb37420bad7?diff=unified#diff-0235ef5497bdd24697b0fdf58e1f088eL96

**Comment by woodbri** [comment] 2015-07-22 17:15
Yes all tests pass on postgresql 9.3. Boost version: 1.54.0 is the default version for Ubuntu 14.04.
I don't think this is critical, but want to let you know because you put in extra effort to remove all the warning.

**Comment by sanak** [comment] 2015-07-22 17:17
Sorry.
I looked the top error message, and above Windows Visual Studio issue may not be related with this.
<pre>
...::_M_current' may be used uninitialized in this function [-Wmaybe-uninitialized]
</pre>

**Comment by cvvergara** [comment] 2015-07-22 17:33
What compiler are you using?

**Comment by woodbri** [comment] 2015-07-22 17:37
```
$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
```

One fix for this in released code would be to add the ``#ifdef DEBUG`` like below since this is only for debugging:
```
#ifdef DEBUG
  graph_traits<graph_t>::edge_iterator ei, eend;
  for (tie(ei, eend) = boost::edges(graph); ei != eend; ei++) {
    dbg("Input Edge %d -> %d cost = %f", graph[*ei].source, graph[*ei].target,
        graph[*ei].cost);
  }
#endif
```

**Comment by yobiSource** [comment] 2015-07-23 05:53
I get the same message during compile.

**Comment by cvvergara** [comment] 2015-07-23 06:13
I'm waiting for boost people to answer to my post:
http://lists.boost.org/boost-users/2015/07/84649.php

**Comment by cvvergara** [comment] 2015-07-27 15:38
As this is a compile warning, generated with -Wall flag on a function that is not being modified in Version 2.1, and that the final release will not have the -Wall flag on, I am moved this issue to a future release.

**Comment by cvvergara** [comment] 2016-02-25 18:34
Deprecating pgr_apspJohnson please use pgr_johnson
pgr_apspJohnson Its being fixed by wrapping it with the results of pgr_johnson

**Closed** 2016-02-25 18:34 UTC
Labels: Comiple Error or Warning, Fixed on dev-2.2, Johnson
