### ISSUE TITLE
KSP gives erroneous results whenever there are edges that share start/end points

### ISSUE THREAD

**Issue by mbasa** [pgRouting/pgrouting#285] opened 2015-02-05 11:12 UTC
- KSP finds only 1 path whenever different edges share the start and end nodes.
- And the resulting path isn't even the Shortest Path.

Very easy to replicate by just creating a network similar to below:

![pg_ksp-error](https://cloud.githubusercontent.com/assets/462884/6059195/b7a8d162-ad69-11e4-9097-86ba06847b9a.png)

![pg_ksp-error2](https://cloud.githubusercontent.com/assets/462884/6059300/cf0c15ac-ad6a-11e4-822e-6e42c0c58796.png)

**Comment by woodbri** [comment] 2015-02-05 15:03
Look at #229 it has a patch that I think resolves this issue.

**Comment by sanak** [comment] 2015-02-07 11:39
Okay, this is one of critical issues for our customer...
I will start to check it.

**Comment by dkastl** [comment] 2015-02-13 17:24
I think this is the forever recurring problem or "parallel edges", which was already an issue with the first implementation of Dijkstra algorithm.

There exists one simple workaround: split those edges into two.

## Code Sample

```
CREATE EXTENSION postgis;
CREATE EXTENSION pgrouting;
```

### "Parallel Edges"

```
CREATE TABLE parallel (
    id serial,
    source integer,
    target integer,
    cost double precision,
    reverse_cost double precision,
    x1 double precision,
    y1 double precision,
    x2 double precision,
    y2 double precision,
    the_geom geometry
);

INSERT INTO parallel (x1,y1,x2,y2) 
    VALUES (1,0,1,1),(1,1,1,3),(1,1,1,3),(1,1,1,3),(1,3,1,4);

UPDATE parallel SET the_geom = ST_makeline(ST_point(x1,y1),ST_point(x2,y2));
UPDATE parallel SET the_geom = ST_makeline(ARRAY[ST_point(1,1),ST_point(0,2),ST_point(1,3)]) WHERE id = 3;
UPDATE parallel SET the_geom = ST_makeline(ARRAY[ST_point(1,1),ST_point(2,1),ST_point(2,3),ST_point(1,3)]) WHERE id = 4;
UPDATE parallel SET cost = ST_length(the_geom), reverse_cost = ST_length(the_geom);
SELECT pgr_createTopology('parallel',0.001);
```
![ksp_parallel](https://cloud.githubusercontent.com/assets/227762/6191830/c6143fd4-b3ef-11e4-8506-7e1b9d41e20d.png)

```
SELECT seq, id1 AS route, id2 AS node, id3 AS edge, cost 
    FROM pgr_ksp(
        'SELECT id, source, target, cost, reverse_cost FROM parallel',
        2, 3, 2, true
);

 seq | route | node | edge | cost 
-----+-------+------+------+------
   0 |     0 |    2 |    4 |    4
   1 |     0 |    3 |   -1 |    0
(2 rows)
```

### Correct Network

```
CREATE TABLE network (
    id serial,
    source integer,
    target integer,
    cost double precision,
    reverse_cost double precision,
    x1 double precision,
    y1 double precision,
    x2 double precision,
    y2 double precision,
    the_geom geometry
);

INSERT INTO network (x1,y1,x2,y2) 
    VALUES (1,0,1,1),(1,1,1,3),(1,3,1,4),(1,1,0,2),
           (0,2,1,3),(1,1,2,1),(2,1,2,3),(2,3,1,3);

UPDATE network SET the_geom = ST_makeline(ST_point(x1,y1),ST_point(x2,y2));
UPDATE network SET cost = ST_length(the_geom), reverse_cost = ST_length(the_geom);
SELECT pgr_createTopology('network',0.001);
```

![ksp](https://cloud.githubusercontent.com/assets/227762/6191838/e9a50ff0-b3ef-11e4-8fe1-1b3b71a39d08.png)

```
SELECT seq, id1 AS route, id2 AS node, id3 AS edge, cost 
    FROM pgr_ksp(
        'SELECT id, source, target, cost, reverse_cost FROM network',
        2, 3, 2, true
);

 seq | route | node | edge |       cost       
-----+-------+------+------+------------------
   0 |     0 |    2 |    2 |                2
   1 |     0 |    3 |   -1 |                0
   2 |     1 |    2 |    4 | 1.41421353816986
   3 |     1 |    5 |    5 | 1.41421353816986
   4 |     1 |    3 |   -1 |                0
(5 rows)
```

**Comment by dkastl** [comment] 2015-02-23 04:33
According to Dave Potts, the issue's origin may be located here:

```
I have found the source of the problem, its in KSPGraph.cpp, at line 78

The input function were it creates the graph has a simple data structure,
if a link has already been defined, a new one with the same set of values
will over write it.
```

**Comment by dkastl** [comment] 2015-02-23 04:38
More information:

```
The problem is caused by the way that Graph.cpp deals stores the data, 
it can only handle a single instance of link, see the code for get_edge_code 
in Graph.cpp line 190.

The code works by using the formal    id*largest-vertext+id where the id's 
are the different vertexs, the results are stored in an array map called 
m_mpEdgeCodeWeight, its acced at line 275 to get a list of values 
between two different ids.
```

... referencing the following files:
* [get_edge_code]( https://github.com/pgRouting/pgrouting/blob/5fc9cff624778f4038e2658433acf9979e28ee8d/src/ksp/src/Graph.cpp#L190-L195)
* [m_mpEdgeCodeWeight](https://github.com/pgRouting/pgrouting/blob/5fc9cff624778f4038e2658433acf9979e28ee8d/src/ksp/src/Graph.cpp#L275-L287)

**Comment by dkastl** [comment] 2015-03-01 16:10
Thank you @cvvergara !
After testing the queries above with the KSP algorithm in branch `vicky-develop` the result is as expected.

**Comment by cvvergara** [comment] 2015-03-06 13:30
Working on this issue, and trying to speed up the overhead time the parallelism generates:
I have this extreme case: Figure 1 (F1 for short)
![multiparallel-issue](https://cloud.githubusercontent.com/assets/5035290/6525810/de71f022-c3cf-11e4-89d3-ed32623056e4.png)
With this graph I will explain how Yen works (except there are no parallel edges in original Yen algorithm, just 1 within 2 nodes) but the idea is the same.
Given first graph of F1, (F1G1 for short) let all the straight edge's value be 1, and curved edges be 2, then the shortest path is indicated with the framed arrow.
so, if that first graph is the initial graph, there are 3x3x3x3=81 possible paths.

In the first cycle: after the initial solution is found (using dijkstra):
1) a is the root path, edge ab will be removed, Dijkstra from a to e is applied and the resulting graph is stored in the heap (Without parallel edges, it will force to look an alternate path that don't start with ab), but we have parallel edges so it will look for one and can be one starting with ab, and In this case the second graph (F1G2) is stored in the heap.
2) ab is the root path, edge  bc is removed, and the trailing path is by doing  dijkstra from b to e  (4th graph, F1G4, sorry for the disorder), and that graph is added to the heap
3) abc is the root path now, cd is removed and the Dijkstra's resulting path is added to the heap (not shown)
4) abcd is the root path and  doing Dijkstra from d to e we get a new path and that one is stored in the heap.
To finish the cycle:
From all the paths found we select the "smallest"  one and put it as a solution.
Say that F1G2 is the found solution. we remove that one from the heap, and go to next cycle.

In second cycle:
1) to do the first Dijkstra: a is the root path edges ab from first and second solution are removed... so the graph looks like F1G3 and Dijkstra is applied to that graph. resulting graph is added to the heap as allways
2) then ab from second graph is the root path, the 2 curved edges from a to b remain, the straigh edge bc is removed and Dijstra from b to e is applied and stored the result in the heap....  etc...
When the cycle ends we get the smallest.
so, for this particular problem all solutions look the same: abcde but with different edges and we can get 81 pahts, where 81 Dijkstra's were done.
![multiparallel-lesssolutions](https://cloud.githubusercontent.com/assets/5035290/6525910/3a76c752-c3d1-11e4-85e3-ef34deccdb34.png)
So, my proposal is: Do we want all 81 paths or with the 9 shown in the second graph is sufficien.
The "straight" path is our solution and we store it as a solution and then:
2 more paths are generated using the other two parallel lines between a and b,  
2 more paths are generated using the other two parallel lines between b and c,  
2 more paths are generated using the other two parallel lines between c and d,  
2 more paths are generated using the other two parallel lines between d and e,
we store all these generated paths into the heap. (all shown in the figure 2)
Then subsequent cycles wont do a single Dijkstra (in this example) because path abcde regardles of the edges is already in the solution. And a max of 9 paths are generated.

**Comment by cvvergara** [comment] 2015-03-06 13:53
(continution from last post...)
For a "normal" problem, I think that most of the time the parallel edges are likely to have similar values so the smallest routes using vertex notation are the same, but the edge notation is going to be different.  
The following figure is a sequence of roundabouts,
![roundaboutssequence](https://cloud.githubusercontent.com/assets/5035290/6526190/8dc2ccdc-c3d4-11e4-89e8-645e2d45dac1.png)
When that sequence (shortest path is in the middle, and accually say that there are 4 roundabouts) is in a solution already found, the next 81 solutions, are likely going to include the same vertices, but different edges, (going around it), do we want the 81 solutions with the same vertices, or just 9 solutions is enough?  is like saying, deviate a little from the shortest path, but go back to it inmediately.

**Comment by cvvergara** [comment] 2015-03-06 13:59
Note: once a solution is found, the rest of the 81 solutions can be found recursevely without doing dijkstras,
The 9 solutions can also be found traversing once the path, which is faster than above, but gives the idea of the paralellism existing in the solution without having all of the solutions.
So, the underlying issue here is WHAT do we want as answer.

**Comment by cvvergara** [comment] 2015-03-06 16:24
Also this is an option I think:
Make sure the orignal code stores the shortest dge, and solves Yen.
Let paralelism be handled by the user with postgres.

**Comment by cvvergara** [comment] 2015-03-06 16:38
Note, the recursively get the 81 solutions or the traversing to get the 9 solutions are just to avoid doing dijkstras, and are added to the heap. and then the parallel edges can be treated as "THE EDGE" in Yen, to get alternative routes.

**Comment by cvvergara** [comment] 2015-03-20 19:33
Fixed with  commit 5cdd106ebe
Parallels are being ignored, but the "its not returning the smallest edge" part of the issue is being fixed.
you can get parallels using a sql query by using the edge id (id3) of the return query with your original data and comparing with the edge id (id3) with the next sequence number of the return query.

**Comment by mrdapotts** [comment] 2015-04-03 13:24
HI 
FAO CVvergara,  I jused tried your solution, ie pgrouting-ksp-detail-fix on the network given in the  pgRouting Manual (2.0.0-dev) and got a different result to the expected one.

ie 
 route | node | edge | cost 
-------+------+------+------
     0 |    0 |    7 |    1
     1 |    0 |    8 |    1
     2 |    0 |    5 |    1
     3 |    0 |    6 |    1
     4 |    0 |    9 |    1
     5 |    0 |   12 |    0
     6 |    1 |    7 |    1
     7 |    1 |    8 |    1
     8 |    1 |    5 |    1
     9 |    1 |    6 |    1
    10 |    1 |   11 |    1
    11 |    1 |   12 |    0
(12 rows)
The route function seems to have become a sequeance number and the node column seems to have become the route number.  This is a change of function design

**Comment by cvvergara** [comment] 2015-04-03 14:44
The manual that applies is also on the ksp-detail-fix
https://github.com/pgRouting/pgrouting/blob/ksp-detail-fix/src/ksp/doc/index.rst
that has this examples:
SELECT seq, id1 AS route, id2 AS node, id3 as edge, cost
FROM pgr_ksp(
  'SELECT id, source, target, cost FROM edge_table',
  7, 6, 2
);

SELECT seq, id1 AS route, id2 AS node, id3 as edge, cost
FROM pgr_ksp(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    7, 6, 2
);

**Comment by cvvergara** [comment] 2015-04-03 15:08
The original data representation of "cost" is with blue lines, the "reverse_cost" is with green+red arrows. And edges with -1 are not inserted.
![fig1-originaldata](https://cloud.githubusercontent.com/assets/5035290/6983933/a1db16c6-d9e0-11e4-86e3-5d601ed16e3a.png)

**Comment by mrdapotts** [comment] 2015-04-03 16:46
Thank you! Do you have an email address? I original wrote the interface code between the ksp library and the pgroute, hence the inerest in the code.

**Comment by cvvergara** [comment] 2015-04-03 17:52
Yes. vicky_vergara@hotmail.com
you can find me also in https://gitter.im/pgRouting/pgrouting when I am in "working" status

**Comment by cvvergara** [comment] 2015-04-03 17:59
@mrdapotts I need your email to send an invitation for the gitter

**Comment by cvvergara** [comment] 2015-04-14 20:09
@mrdapotts 
I am trying to understand the test query in  ksp-any-01.test:
```
select ksp.id1, ksp.id3, n.source, n.target, round(st_length(n.the_geom)::numeric, 2) as len
  from pgr_ksp(
    'select source, target, cost,reverse_cost, id from network order by id',
    4,  5,  15,  'f') ksp,
        network n
 where ksp.id3 = n.id
 order by ksp.id1, ksp.id3;
```

VS  this one  (I want to change it to this one) which will test that all the columns of pgr_ksp output remains the same across versions.
```
select seq, id1 as route, id2 as node, id3 as edge, round(cost::numeric,2) as cost from pgr_ksp(
    'select source, target, cost, id from network order by id',
    4,  5, 15,  'f')
```
 here is the graph of the data:
![graphofdata](https://cloud.githubusercontent.com/assets/5035290/7146176/45e5b918-e2b7-11e4-8fd8-37c89efd4576.png)

 here is the detail of the edges that go from 4 to 5:
![graphofdata1](https://cloud.githubusercontent.com/assets/5035290/7146225/b2fbbec6-e2b7-11e4-9738-831287fdb7a6.png)

**Comment by cvvergara** [comment] 2015-04-21 00:18
In  https://github.com/pgRouting/pgrouting/wiki/Handling-parallels-after-getting-a-path-%28pgr_ksp-focus%29
There is an idea of how to handle parallels once a route(s) is given. Based on this image.
![the_picture](https://cloud.githubusercontent.com/assets/5035290/7243360/d8d24f96-e791-11e4-974a-d90a99feb0d3.png)

**Closed** 2015-07-17 01:48 UTC
Labels: Fixed on Develop
