### ISSUE TITLE
CMakeLists.txt needs an option to select PG version

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#301] opened 2015-03-15 14:51 UTC
Currently if you have multiple versions of Postgresql installed on your system, which is common for a server supporting a cluster, cmake will only compile pgRouting against the latest version of postgresql. For example if you have versions 9.2, 9.3, 9.4 installed, you can only build pgRouting against 9.4.

We need to add a cmake option -DWITH_PG_VER=9.2 that will allow you to build against a specific version. On Ubuntu 14.04 there is ``/usr/share/cmake-2.8/Modules/FindPostgreSQL.cmake`` that has the option to set PostgreSQL_ADDITIONAL_VERSIONS before calling find_package(PostgreSQL) that will make the defined version the preference if found. Unfortunately it is not compatible with our existing code and some changes will need to be made.

**Comment by woodbri** [comment] 2015-03-15 17:08
This seems to be complicated by the fact that there is a bug on Ubuntu that seems to be getting in the way also.

**Comment by woodbri** [comment] 2015-03-15 17:49
Thinking that maybe a better option would be -DWITH_PG_CONFIG=/path/to/pg_config because this would allow us to find and extract all the variables needed from that pg_config file otherwise we will just find the default one on the system.

**Comment by woodbri** [comment] 2015-06-26 14:06
I have added cmake option -DPG_VERSION=x.y so you can select which version to build with in the develop branch. Reopened until release and tagged as fixed in develop.

**Comment by cvvergara** [comment] 2015-06-26 14:29
Q. by default it will still get the latest version?

**Comment by cvvergara** [comment] 2015-06-26 14:46
@robe2 Regina:
I went to see the Jenkins, and the build for Windows is marked as failure.

**Comment by cvvergara** [comment] 2015-06-26 14:54
Maybe this change affects the way you set up Jenkins?

**Comment by woodbri** [comment] 2015-06-26 15:46
It will (at least on Linux) pickup the the latest version installed on the system.
And it "should" not change the behavior if you leave it off.
Obviously this is not true on Windows, I'll look at the logs on winnie and see if I can figure out what is happening there.

**Comment by cvvergara** [comment] 2015-06-26 15:59
Maybe this needs to be updated also:
https://github.com/pgRouting/pgrouting/blob/develop/doc/src/installation/build.rst
I am tagging as documentation.

**Comment by woodbri** [comment] 2015-06-26 16:01
OK, I will correct the above, we no longer search the PATH variable for pg_config because when you have multiple version installed only the last or latest one is installed in the path. So I might need to add an explicit path for Windows. 

-- CMAKE_PREFIX_PATH=/usr:/usr/local:/c/ming64/projects/pgx64/pg92
-- PG_VERSION in FindPostgreSQL.cmake is *
-- POSTGRESQL_EXECUTABLE is e:/jenkins/postgresql/rel/pg9.4w64gcc48/bin/postgres.exe
-- POSTGRESQL_PG_CONFIG is POSTGRESQL_PG_CONFIG-NOTFOUND

I think this should get set as part of CMAKE_PREFIX_PATH=

**Comment by robe2** [comment] 2015-06-26 17:30
Seems like I have a bunch of things going on not related to this -- though  see that it can't determine the PostgreSQL version.

Why is /c/ming64 hardcoded in CMAKE_PREFIX_PATH?

**Comment by woodbri** [comment] 2015-06-26 18:08
I think this was because when we originally ported the build environment to mingw we had all the dependencies in the projects directory. Feel free to update the if(WIN32) block of code as needed. We can add additional paths in the WIN32 section as needed.

**Comment by robe2** [comment] 2015-06-26 19:52
Well ideally I'd wont to send those via a Jenkins environment variable cause I have a different setup for each build, so it's not just one path.  Not sure how to do that with it embedded in a CMakeLists somewhere. At anyrate that path you have I don't even have anymore since it was a very old ming64 install that had that.

**Comment by woodbri** [comment] 2015-06-26 20:29
in cmake we can read environment variables like: ``$ENV{OS_BUILD}`` so you could define a variable that we can pick up. It might also be useful to just add a optional variable to the command line like: ``-DWITH_PG_CONFIG=/path/to/pg_config``

**Comment by robe2** [comment] 2015-06-28 18:11
I can work with either.  Not sure which is most useful for others. You'd be better to judge.  I imagine other package maintainers might have similar issue where they have a custom postgres just for building that they want picked up.

**Comment by sanak** [comment] 2015-06-29 01:51
The latest `develop` branch can't be built on Mac OSX homebrew environment.
Here is the result of executing `cmake -DWITH_DD=ON ../` command.
<pre>
:
-- PGROUTING_GIT_TAG: pgrouting-2.0.0
-- PGROUTING_GIT_BUILD: 280
-- PGROUTING_GIT_HASH: 0acd2ea
-- PGROUTING_GIT_BRANCH: develop
-- PGROUTING_VERSION_REVISION_NAME: 0acd2ea develop
-- PGROUTING_VERSION_REVISION_HASH: 0acd2ea
-- PG_VERSION: *
-- UNIX=1
-- WIN32=
CMake Warning (dev) at CMakeLists.txt:123 (find_package):
  Syntax Warning in cmake code at

    /Users/sanak/Build/cpp/pgrouting-git/cmake/FindPostgreSQL.cmake:30:60

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- PG_VERSION in FindPostgreSQL.cmake is *
-- POSTGRESQL_EXECUTABLE is /usr/local/bin/postgres
-- POSTGRESQL_PG_CONFIG is POSTGRESQL_PG_CONFIG-NOTFOUND
-- PostgreSQL not found.
CMake Error at CMakeLists.txt:125 (message):
   Please check your PostgreSQL installation.


-- Configuring incomplete, errors occurred!
</pre>

I confirmed that removing the following line `NO_DEFAULT_PATH` worked without problem.
https://github.com/pgRouting/pgrouting/blob/bbc96fc13538e5385287a8edad0bbd14121647c4/cmake/FindPostgreSQL.cmake#L37

By the way, about `WITH_PG_CONFIG` parameter,
I think that just using current `POSTGRES_PG_CONFIG` is enough,
because in my feeling, `WITH_` means boolean (ON/OFF) parameter.
(So, it will be like `-DPOSTGRES_PG_CONFIG=/path/to/pg_config`,
after modifying the following part to use specified value.)
https://github.com/pgRouting/pgrouting/blob/bbc96fc13538e5385287a8edad0bbd14121647c4/cmake/FindPostgreSQL.cmake#L26

**Comment by cvvergara** [comment] 2015-07-15 00:18
Unfortunately the change to handle many postgresql versions in the same system doesn't work for Mac or for windows. So develop for the moment only works for linux.

**Comment by woodbri** [comment] 2015-07-16 20:42
I just pushed develop and added a commandline option ``-DPOSTGRESQL_BIN=/usr/lib/postgresql/9.3/bin/`` this can be used to select a specific version of postgres by pointing to bin directory where pg_config is expected to be found. I reverted the previous change so it should work like it did before if this option is not included.

**Comment by cvvergara** [comment] 2015-07-16 20:56
This one is wierd.
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/1994/console

the others compile but does not run the tests:
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/1993/console
RUNNING: test-runner.pl -pgisver 2.1.7 -pgport 10444 -ignorenotice
psql: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 10444?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 10444?

**Comment by cvvergara** [comment] 2015-07-16 20:58
the error might be somewhere because Travis desnt run the tests.
https://travis-ci.org/pgRouting/pgrouting/jobs/71321190#L1371

**Comment by cvvergara** [comment] 2015-07-16 21:09
I dont have the problem in develop_2_1_0

**Comment by woodbri** [comment] 2015-07-16 21:16
But you have also had @robe2 make changes to develop_2_1_0 and develop has been dormant because I broke it with the prior change. Hopefully @robe2 can look at this because I think there is a problem with the system configuration and setup scripts.

**Comment by cvvergara** [comment] 2015-07-16 21:19
what if,  that change is reverted in develop,  I merge develop_2_1_0 into develop, then you branch from develop to a different branch and we ask @robe2  to track that branch while you add the necessary code to make it work on travis and on windows, when you are done we ask @sanak to test it on Mac.

**Comment by robe2** [comment] 2015-07-16 21:38
@woodbri , @cvvergara   sorry -  http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/1994/console is my fault.  I upgraded my 32-bit 9.3 to a newer gcc chain and neglected to change the develop one to stop testing the old gcc.  Should be fixed now.

**Comment by cvvergara** [comment] 2015-07-16 21:44
@robe2 Regina: 
Thank you very much.
P.D.
This one failed,
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/1999/console
But 3 out of 4, I am going to merge, and lets see what happens on travis and winnie.

**Closed** 2015-07-17 01:55 UTC
Labels: Bug Report, Documentation, Feature Request, Fixed on Develop
