### ISSUE TITLE
pgr_flipedges

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#322] opened 2015-04-03 05:29 UTC
Referring to #309 we should rename `pgr_flipedges` to `_pgr_flipedges` and provide a wrapper (returning a notice) to ensure backwards compatibility.

**Comment by cvvergara** [comment] 2016-02-25 18:59
@woodbri 
Documentation has the following Warnings:
  -  No checking is done for edges that do not connect.
  -  Input geometries MUST be LINESTRING or MULTILINESTRING.
  -  Only the first LINESTRING of a MULTILINESTRING is considered.

No checking is done for edges that do not connect.
  - is checking missing?
  - what happens when they don't connect?

- MULTILINESTRING, why would we use use MULTILINESTRING in pgrouting, maybe I dont understand, but it makes no sense to me, because then you can have a segment here, and a segment there, and no connection between segments.

- does it check if they belong to the same SRID?

- I can deduce from the documentation that is for post processing 

- I wonder if you can make an example that uses the sample data

**Comment by cvvergara** [comment] 2016-04-29 17:52
Yesterday I had a talk with a user,
He asked me how to put the edges in the correct direction, and I mentioned this function.
The [documentation](http://docs.pgrouting.org/2.2/en/src/convinience/doc/pgr_flipEdges.html) does not provide any insight on how to us it in the context of any routing functionality of pgRouting.

By looking at it, I see that it receives an array.  why??? if the data returned by any of the routing functionality is as set of record, not an array.

So let me put this situation: project A & project B & project C etc....
both are interested on displaying on a map a nice route with a line with arrows on it, and the arrows should be on the correct direction of the geometry
but
* project A wants to display the total cost of the route when the arrow passes above the line
* project B wants to display the name of the street when passing over the line. (the name of the street is different for each section of the line)
* project C wants to display the number of houses on the line
* project D wants ......

Suppose that the additional information:
A) is in an additional column in edge_table
B) is in another table
The commonality is that all of them want the correct direction of the arrows. so some segments have to be reversed, the non commonality is that one might be using pgr_dijkstra(one to one), other pgr_dijkstra(one to many), etc.

So, not only the geometries are to be "corrected", but the additional information is different.

In this example I am interested in the cost and the name of the street
```
WITH
result AS ( select * from pgr_dijkstra(one to one) ),
SELECT seq, result.cost AS time, edge_table.name
   CASE
       WHEN result.node = edge_table.source
            THEN edge_table.the_geom
       ELSE ST_Reverse(edge_table.the_geom)
       END AS path_geom
FROM edge_table JOIN result
  ON edge_table.id = result.edge 
  ORDER BY result.seq;
```

In this other example I am interested in the cost and the length of the street
```
WITH
result AS ( select * from pgr_dijkstra(one to many) ),
SELECT seq, result.end_vid, result.cost AS time, edge_table.length_m
   CASE
       WHEN result.node = edge_table.source
            THEN edge_table.the_geom
       ELSE ST_Reverse(edge_table.the_geom)
       END AS path_geom
FROM edge_table JOIN result
  ON edge_table.id = result.edge 
  ORDER BY result.seq;
```

I really don't see why a function to do:
   CASE
       WHEN result.node = edge_table.source
            THEN edge_table.the_geom
       ELSE ST_Reverse(edge_table.the_geom)
       END AS path_geom

is needed to put the geometries stored on the edge_table on the "correct" direction.
Everything surrounding that CASE statement will be different, and I hardly see a function that will satisfy all the requirements of all the projects.

**Comment by dkastl** [comment] 2016-05-01 05:24
What a long comment ;-)
Honestly, I have problems to get the point right now.

I use "flip edges" also in the workshop. There are cases, where you want to know for example, how far you got in a certain time, and you want to know the point, that can be within a source and target node. But source and target of an edge can be in the reverse order.

Right now I can't think of anything else than the Geometry, where this problem applies to. Are there any other common attributes, than depend on the order of source and target?

**Comment by woodbri** [comment] 2016-05-01 13:59
The original purpose for flipedges was to support my driving directions code where I needed athe segments oriented along the path of the route so I could analyze them for generating maneuvers and later for generating a polyline for rendering the path. 

Regarding checking, I think it is a reasonable assumption that we are working with a computed route because this is pgRouting and not the more general postgis function. So routes should be a continuous (connected) list of edges, it should be all in the same srid so we do not need to check these things.

If flipedges is called with the results of a route, then you have the edge_id and the node_id which simplifies the problem to determining if the edge needs to be flipped, but I just  ran into a scenario where I was only given the edge_id's that had been saved in a table and had to flip the edges without the aide of the node_ids. This can be done in sql with lead() and lag() window functions rather than using an array of ids or an array of geometries.

**Comment by woodbri** [comment] 2016-05-01 13:59
Opp, didn't mean to close it.

**Comment by cvvergara** [comment] 2016-05-02 02:01
@dkastl 
Q1- where in the workshop do you use pgr_flipedges? I could not find it.
the closest thing that I found is that you dont use it in this wrapper:
http://workshop.pgrouting.org/chapters/wrapper.html
but you do flip edges without this function.
Q2- I am confused, if you are using the pgr_flipedges then why do you want it to be with underscore

@woodbri 
"but I just ran into a scenario where I was only given the edge_id's that had been saved in a table and had to flip the edges without the aide of the node_ids."
Q1- Form the routing functions that pgRouting returns, which one is the one that is not giving the edges & nodes information?
Q2- If from your problem, you didn't get the results from pgRouting, why add a function that is not using pgRouting knowing that pgRouting returns the information given to be able to flip edges using a simple CASE statement?

**Comment by dkastl** [comment] 2016-05-02 02:04
Right, I don't use the function. I just flip edges. I actually forgot, that there is a function for that.
I'm not sure, if it's necessary to have a function for the pgRouting user to do this. No strong opinion about this though.

**Comment by cvvergara** [comment] 2016-05-02 02:23
I have an extra Q,
What do I answer to the user that he should use, this function?:
You should use this function: first, make sure that you don't have the nodes information, and then this function will flip the edges. And there is no way that you can have that information back, for example, you can not re run the query and save all the necessary information, you can not redesign you application to save the needed information.

```
WITH
result AS ( select * from pgr_dijkstra(one to one) ),
geometry AS  (SELECT array_agg(edge_table.the_geom) AS geomarray 
   FROM edge_table JOIN result  ON edge_table.id = result.edge 
  ORDER BY result.seq)
fliped AS (SELECT unnest(pgr_flipedges(geomarray)))
-- left to the reader on how to join the flipped edge to the original data
```

Otherwise you can use this:
```
WITH
result AS ( select * from pgr_dijkstra(one to one) ),
SELECT seq, result.cost AS time, edge_table.name
   CASE
       WHEN result.node = edge_table.source
            THEN edge_table.the_geom
       ELSE ST_Reverse(edge_table.the_geom)
       END AS path_geom
FROM edge_table JOIN result
  ON edge_table.id = result.edge 
  ORDER BY result.seq;
```

**Comment by dkastl** [comment] 2016-05-02 02:30
> What do I answer to the user that he should use, this function?:
If it's a real user, tell to ask the mailing list instead of sending direct emails ;-)

At least it's necessary to  understand, that this is a new and "experimental" function. Like in the workshop, with a bit of pgsql you can write your own function. So I wouldn't say "should use", but "can use" being aware of the consequences, that the function may change in future releases.

**Comment by woodbri** [comment] 2016-05-02 05:03
@cvvergara the missing nodes is not an issue with the function, it was because the user stored only the edge_ids in a table so I had to reconstruct the path based only on that.

I think flipedges is a commonly needed utility function as documented by the fact the I wrote one, @cvvergara and @dkastl and probably others have all had to think about it and write a function. If there is a general need then I think that warrants adding it to the product.

**Comment by dkastl** [comment] 2016-05-02 05:20
@woodbri I think the question, what should be part of the library and what shouldn't, is an always recurring issues. We had it with version 1.x as well.

There is always a trade-off between being nice to users and provide a lot of convenient utility functions and the problem to have to maintain many functions.

In the past we had the idea of the `pgrouting-contrib` repository, which didn't work. Then there was the Wiki page with links to Gists, which probably didn't work either.
There is also a list of HowTo pages on the pgRouting website, which isn't maintained well, but I believe, that users look at it.

I think have some recipes or additional workshop chapters might be another approach. One very often requested feature is driving directions, where "flip edges" becomes useful. Maybe we should just add more workshop content, so users can study typical problems and take it as a starting point for their own custom code.

Somehow I feel we're already adding too much functions again to pgRouting. I would like to keep the number as low as possible. It's acceptable to have an outdated example or recipe. Not nice of course, but better than having some functions, that are not maintained well enough.

Just some thoughts during holiday.

**Comment by dkastl** [comment] 2016-05-02 05:22
And I forgot, that Regina's book will also help to have more examples to learn from.

**Comment by robe2** [comment] 2016-06-15 18:57
I'll add an an example in the application building part to demonstrate using @cvvergara  http://talks.vicky.georepublic.info/howto/flipGeometries.html

I've always done it by using ST_Reverse and Case too for 2 reasons:

1.  I don't generally have an array of linestrings to begin because pgr_dijkstra returns a of rows, so would have to aggregate to use this.

2. This function assumes that linestrings start and end will snap, which they may not because of floating point precision, so still better to go by node ids.

3. I think I mentioned this before but the _pgr_startpoint, _pgr_endpoint are relativly costly functions because they wrap another postgis function and are written in plpgsql.

**Comment by cvvergara** [comment] 2016-06-15 19:02
Also, its not a routing function.

I would like to deprecate this proposed function.

Please put thumbs up for deprecating.

**Comment by cvvergara** [comment] 2016-06-15 19:45
Note: it can be placed in this repository:
https://github.com/pgRouting/pgrouting-contrib

**Comment by dkastl** [comment] 2016-06-16 03:48
I think the reason for `_pgr_startpoint`. `_pgr_endpoint` was, that some people have multi-geometries.
But I think it's better to let them fix this problem, because if you really have multi-linestrings, then you have a problem. And if your type is multi-linesting only, then it's no big deal to change this.

Flip edges is also enough to put it in the workshop or some HowTo.

**Comment by woodbri** [comment] 2016-06-16 04:01
The reason for _pgr_startpoint and _pgr_endpoint is because by default shp2pgsql creates multi-objects and shapefiles are the most common defacto standard for distributing GIS data. The problem is not a user problem but more likely a vendor problem with whomever is creating the GIS data. 

You can declare that these issues are user's problems to deal with, but that typically turns the problem into a support problem where we get bombarded with questions on how to fix it or work around it. But its your call. Maybe there should be a document that has common problems and solutions that we can point users to.

**Comment by cvvergara** [comment] 2016-06-16 04:45
I'll add some links:
Current documentation:
http://docs.pgrouting.org/2.2/en/src/convinience/doc/pgr_flipEdges.html#pgr-flip-edges
Current Code:
https://github.com/pgRouting/pgrouting/blob/master/src/convinience/sql/pgrouting_conversion_tools.sql#L77

**Comment by dkastl** [comment] 2016-06-16 05:10
@woodbri what about notifying a user, when there are multilinestrings, for example when someone runs "pgr_createTopology"?

I see the following issue:
* When someone really has multi-geometries, the user had to fix that. With our approach we just take the first geometry and forget about the rest. So it will give wrong results.
* When someone has used the default settings of shp2pgsql for example, why is it a problem to change it into a LINESTRING geometry? We could also do this automatically, when we run "pgr_createTopology". It would have the same effect, if someone has really multi-geometries as data would get lost.

I'm not sure we should be friendly to users in a way that we workaround wrong settings. If you run `ST_startPoint`, it also won't work with multi-geometries.

PostGIS documentation has similar argument: http://postgis.net/docs/ST_StartPoint.html

**Comment by cvvergara** [comment] 2016-06-16 05:18
Also, if constructed with pgr_createTopology and given a tolerance, the original edges that don't snap "physically" won't be reversed, because it wont have the same starting/ending value

**Comment by woodbri** [comment] 2016-06-16 13:27
I don't have a strong opinion on this. So change it how you think is best. 

The st_startpoint() problem exists because the old postgis behavior was to return the first point of linestring or multilinesting and then they changed that behavior, but that was awhile ago so its probably less of an issue now.

**Comment by cvvergara** [comment] 2016-08-24 19:02
The concept `edge` in pgRouting: has a source and a target,  s -> t and a cost (and optionally a reverseCost) associated to it.  Its not compulsory to have a geometry to do a query with pgRouting.

pgr_flipEdges is a front end driven function and  the intention is to flip geometries.

Application *A*, needs to flip the geometry and application *B*, besides the flipped geometry that needs to get another column that is crucial for their application.

Get the geometry, when there is a geometry involved, and flipping the geometry can be done with postgreSQL/postGIS functions other valuable data can also be obtained while flipping the geometry, if done properly.

I made this [how to flip geometries](http://talks.vicky.georepublic.info/howto/flipGeometries.html#/)that use the sample data of the documentation

There is also the [workshop](http://workshop.pgrouting.org/2.1.0-dev/en/index.html) that show how to flip Geometries.

**Closed** 2016-08-25 00:53 UTC
Labels: Deprecate, Proposed Function
