### ISSUE TITLE
pgr_withPoints: Wrong result when a POI with fraction = 1 is on the shortest path

### ISSUE THREAD

**Issue by NasNasingud** [pgRouting/pgrouting#2253] opened 2022-02-28 09:33 UTC
**Problem**
The function pgr_withPoints does sometimes not output the shortest path. If there is a POI on the shortest path having fraction = 1 (= on a node), this node is ignored for the shortes path calculation. This can lead to considerable detours. However, if the POI with fraction = 1 is removed from the poi_table, the correct result is provided.

**To Reproduce**
Let's produce a very simple graph with only two nodes and two edges. A short one (cost = 10) and a long one (cost = 100):
```
CREATE TEMPORARY TABLE edge_table (id integer, source integer, target integer, cost float);
INSERT INTO edge_table VALUES (1, 10, 11, 10.0);
INSERT INTO edge_table VALUES (2, 10, 11, 100.0);
```
Then we need three POIs. The start POI 20 on the middle of the short edge, the target POI 21 at nearly the end of the long edge. A third POI 22 is located exactly at the end of the long edge (=on node 11):
```
CREATE TEMPORARY TABLE poi_table (pid integer, edge_id integer, fraction float);
INSERT INTO poi_table VALUES (20, 1, 0.5);
INSERT INTO poi_table VALUES (21, 2, 0.9);
INSERT INTO poi_table VALUES (22, 2, 1);
```
When executing the function, I expect the shortest route via node 11. However, when querying the full POI table, the result gives the route via the much longer edge 2:
```
SELECT * FROM   pgr_withPoints(
'SELECT id, source, target, cost FROM edge_table',
'SELECT pid, edge_id, fraction FROM poi_table',
    -20,
    -21,
    false);
```
Result:
```
1	-20	1	5.0	0.0
2	10	2	90.0	5.0
3	-21	-1	0.0	95.0
```

**Workaround**
When the POI query ignores POI 22, the shortest path is given as expected:
```
SELECT *
FROM   pgr_withPoints(
'SELECT id, source, target, cost FROM edge_table',
'SELECT pid, edge_id, fraction FROM poi_table WHERE pid != 22',
    -20,
    -21,
    false);
```
Result:
```
1	-20	1	5.0	0.0
2	11	2	10.0	5.0
3	-21	-1	0.0	15.0
```

**Hint**
It seems, as if a fraction = 0 does not lead to any problems.

**Platform/versions**
```
SELECT version(); -- PostgreSQL 12.9
SELECT postgis_full_version(); -- POSTGIS="3.0.0 r17983"
SELECT pgr_version(); -- 3.3.0
```

**Comment by cvvergara** [comment] 2022-03-07 19:05
Please check #760 and let me know if it gives you on how to handle the problem while the issue is fixed internaly on pgRouting

**Comment by NasNasingud** [comment] 2022-03-08 08:02
Thanks for linking issue #760. The problem is well described there.

In fact, I already ended up to query the real vertice IDs when I get a fraction of 0 or 1 (according to **way around 1** in the linked issue) and that seems to work fine.

**Comment by cvvergara** [comment] 2022-03-09 14:26
Closing because its a duplicate of #760

**Closed by cvvergara** 2022-03-09 14:26 UTC
