### ISSUE TITLE
No Homebrew Formula for v2.1.0

### ISSUE THREAD

**Issue by andrewthornton** [pgRouting/pgrouting#416] opened 2015-10-07 18:09 UTC
`brew install pgrouting` currently installs v2.0.0, not the latest v2.1.0.

**Comment by sanak** [comment] 2015-11-28 00:26
Well, I will try to update homebrew formula with moving current v2.0.0 formula to homebrew/versions.

**Comment by sanak** [comment] 2015-12-15 09:38
Sorry, I confirmed that pgRouting v2.1.0 formula was already updated...
I am sending v2.0.1 formula's pull request to homebrew/versions.
https://github.com/Homebrew/homebrew-versions/pull/1083

**Comment by cvvergara** [comment] 2015-12-15 19:58
@sanak 
Thanks for the information.
Please, can you close this when the process is finished.

**Comment by sanak** [comment] 2015-12-16 07:51
@cvvergara
Okay.

**Comment by cvvergara** [comment] 2016-02-26 03:16
@sanak 
Can this issue be closed, its being 2 months since the processes started and its about V2.1
we can open one later if needed for V2.2

**Comment by sanak** [comment] 2016-03-13 01:41
@cvvergara 
Sorry, I missed about replying the pull request,
but I am thinking to create "pgRouting/homebrew-versions" repository.
(Then it becomes not necessary to think about quite restrict "homebrew-versions" things which is described at [here](https://github.com/Homebrew/homebrew-versions#acceptable-formulae).)
So, please keep this ticket for above task. (If necessary, I will modify the title.)

**Comment by cvvergara** [comment] 2016-03-14 22:32
@sanak 
Ok, thanks for confirmation.

**Comment by cvvergara** [comment] 2016-08-24 19:33
@sanak 
I dont know what to do with this issue, is is still valid? I am about to do a 2.3
is the formula somehow incorporated on the repository?

**Comment by cvvergara** [comment] 2017-04-17 16:39
About formula:
I don't know about 2.1, but I know 2.4 (2.4.1) formula is ready
https://github.com/Homebrew/homebrew-core/pull/11365

Because it is better to use 2.4 instead of 2.1, I will close this issue.

**Closed by cvvergara** 2017-04-17 16:39 UTC
